---
---

title: Revati Pawar
logo: /assets/profile_icon.jpg
description: Data Scientist Portfolio
show_downloads: false
theme: jekyll-theme-minimal

# Social links
social_links:
  linkedin: "https://www.linkedin.com/in/revatipawar29/"
  github: "https://github.com/revatip2"
  email: "rpawar@usc.edu"

# Navigation links
nav:
  - name: "About"
    href: "#about"
  - name: "Education"
    href: "#education"
  - name: "Experience"
    href: "#experience"
  - name: "Projects"
    href: "#projects"
  - name: "Skills"
    href: "#skills"
  - name: "Contact"
    href: "#contact"

# Plugins
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
