title: Revati Rajesh Pawar
logo: /assets/profile_icon.jpg
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal

# Social Links
linkedin: https://www.linkedin.com/in/revatipawar29/
email: rpawar@usc.edu
github: https://github.com/revatip2
